dataset_name: 'kirp'  
paths:
  source_dir: "/project/hnguyen2/mvu9/datasets/TCGA-datasets/KIRP"
  save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp"
  patch_h5_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/patches_h5"
  # patch_png_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/patches_png"
  patch_png_dir:
    patch_256x256_10x: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/png_patches/patch_256x256_10x"
    patch_256x256_5x:  "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/png_patches/patch_256x256_5x"  
  mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/masks"
  only_mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/only_masks"
  stitch_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/graph_1024"
  slide_name_file: "/project/hnguyen2/mvu9/datasets/TCGA-metadata/KIRP/slides.xlsx"
  uuid_name_file: "/project/hnguyen2/mvu9/datasets/TCGA-metadata/KIRP/uuids.xlsx"
  preset_file: "/project/hnguyen2/mvu9/folder_04_ma/wsi-data/presets/tcga_vilamil.csv"
  slide_list:  "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/process_list_autogen.csv" 
  missing_patches_h5: "/project/hnguyen2/mvu9/processing_datasets/missing_files/patches_h5/kirp.csv"
  missing_pt_files: "/project/hnguyen2/mvu9/processing_datasets/missing_files/pt_files/kirp.csv" 
  manifest_dir: "/project/hnguyen2/mvu9/download_tcga/gdc-client/manifest/KIRP"

  # clip_rn50_features_path: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/clip_rn50_features" 
  clip_rn50_features_path: 
    patch_256x256_10x: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/clip_rn50_features_fp/patch_256x256_10x" 
    patch_256x256_5x:  "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/clip_rn50_features_fp/patch_256x256_5x" 
  conch_features_path: 
    patch_256x256_10x: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/conch_features_fp/patch_256x256_10x" 
    patch_256x256_5x:  "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/conch_features_fp/patch_256x256_5x" 
  quilt_features_path: 
    patch_256x256_10x: "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/quilt_features_fp/patch_256x256_10x" 
    patch_256x256_5x:  "/project/hnguyen2/mvu9/processing_datasets/processing_tcga_256/kirp/quilt_features_fp/patch_256x256_5x" 
    
 
# Processing parameters
processing:
  patch_size: 1024
  step_size: 1024
  patch_level: 0
  seg: true
  patch: true
  stitch: false
  auto_skip: true


clip_feature_extraction:
  model_name: clip_RN50  # or clip_ViTB32, resnet50_trunc, model_dino, etc.
  batch_size: 64 
  assets_dir: /project/hnguyen2/mvu9/pretrained_checkpoints  # only needed for DINO or other custom models ckpt_path = os.path.join(args.assets_dir, f'{args.model_name}.pth')
  cache_dir: /project/hnguyen2/mvu9/model_cache  # clip.load("ViT-B/32", download_root=args.cache_dir)
 

conch_feature_extraction:
  model_name: conch_v1
  batch_size: 64
  target_patch_size: 224
  slide_ext: .svs
  no_auto_skip: false
  assets_dir:  /project/hnguyen2/mvu9/pretrained_checkpoints/conch_checkpoints/pytorch_model.bin

quilt_feature_extraction:
  model_name: quilt
  batch_size: 64
  target_patch_size: 224
  slide_ext: .svs
  no_auto_skip: false 
  assets_dir:  /project/hnguyen2/mvu9/pretrained_checkpoints/QuiltNet-B-32 
